/*
var data = [
    {   
        "foto": "images/musica4.jpg",
        "evento": "Concierto de Jazz en el parque",
        "fecha": "14 de febrero",
        "direccion": "providencia #2800",
        "categoría": "Música",
        
    },
    {  
        "foto": "images/musica1.jpg",
        "evento": "Fiesta de los abrazos",
        "fecha": "7 de enero",
        "direccion": "Parque O'Higgins",
        "categoría": "Música",
    },
    {
        "foto": "images/musica2.jpg",
        "evento": "Big Band Concert",
        "fecha": "26 marzo",
        "dirección": "Tobalaba #3600",
        "categoría": "Música",
    },
    {
        "foto": "images/musica3.jpg",
        "evento": "Le rock fest 2018",
        "fecha": "5 de abril",
        "dirección": "Jose Manuel Infante #1415",
        "categoría": "Música",
    },
    {
        "foto": "images/cine1.jpg",
        "evento": "Peliculas en el parque",
        "fecha": "26 de diciembre",
        "dirección": "Parque Bicentenario",
        "categoría": "Cine",
    },
    {
        "foto": "images/cine2.jpg",
        "evento": "Ciclo de cine clásico en Cine Arte Normandie",
        "fecha": "25 de febrero",
        "dirección": "Tarapaca #1520",
        "categoría": "Cine",
    },
    {
        "foto": "images/cine3.jpg",
        "evento": "Proyeccion: 'Star Wars: Los ultimos Jedi'",
        "fecha": "10 de Enero",
        "dirección": "Av. Ossa 655, La Reina",
        "categoría": "Cine",
    },
    {
        "foto": "images/cine4.jpg",
        "evento": "Festival de Cine UC",
        "fecha": "14 de Enero",
        "dirección": "Centro de Extension UC, O'Higgins, Av Libertador Bernardo O'Higgins 390, Santiago",
        "categoría": "Cine",
    },
    {
        "foto": "images/diseño1.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Diseño",
    },
    {
        "foto": "images/diseño2.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Diseño",
    },
    {
        "foto": "images/diseño3.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Diseño",
    },
    {
        "foto": "images/diseño4.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Diseño",
    },
    {
        "foto": "images/teatro1.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Teatro",
    },
    {
        "foto": "images/teatro2.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Teatro",
    },
    {
        "foto": "images/teatro3.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Teatro",
    },
    {
        "foto": "images/teatro4.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Teatro",
    },
    {
        "foto": "images/danza1.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Danza",
    },
    {
        "foto": "images/danza2.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Danza",
    },
    {
        "foto": "images/danza3.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Danza",
    },
    {
        "foto": "images/danza4.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Danza",
    },
    {
        "foto": "images/literatura1.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Literatura",
    },
    {
        "foto": "images/literatura2.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Literatura",
    },
    {
        "foto": "images/literatura3.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Literatura",
    },
    {
        "foto": "images/literatura4.jpg",
        "evento": "",
        "fecha": "14 de Enero",
        "dirección": "",
        "categoría": "Literatura",
    };

]
*/